head_node_type:
  name: head-node-type
  instance_type: m5.xlarge
  resources:
    cpu: 0
worker_node_types: []
auto_select_worker_config: true
# TODO(shomil): remove once set by default in OA
aws:
  TagSpecifications:
    - ResourceType: instance
      Tags:
        - Key: as-feature-enable-multi-az-serve
          Value: "true"
        - Key: as-feature-multi-zone
          Value: "true"
