head_node_type:
  name: head-node-type
  instance_type: m5.4xlarge
  resources:
    cpu:
    gpu:
    memory:
    object_store_memory:
    custom_resources:
      head_node: 1
      accelerator_type_cpu: 1
worker_node_types:
- name: cpu-worker
  instance_type: m5.xlarge
  resources:
    cpu:
    gpu:
    memory:
    object_store_memory:
    custom_resources:
      worker_node: 1
      accelerator_type_cpu: 1
  min_workers: 0
  max_workers: 100
  use_spot: false
- name: gpu-worker-g4-1
  instance_type: g4dn.2xlarge	
  resources:
    cpu:
    gpu:
    memory:
    object_store_memory:
    custom_resources:
      worker_node: 1
      "accelerator_type:NVIDIA_TESLA_T4": 1
  min_workers: 0
  max_workers: 100
  use_spot: true
  fallback_to_ondemand: true
- name: gpu-worker-g4-4
  instance_type: g4dn.12xlarge	
  resources:
    cpu:
    gpu:
    memory:
    object_store_memory:
    custom_resources:
      worker_node: 1
      "accelerator_type:NVIDIA_TESLA_T4": 1
  min_workers: 0
  max_workers: 100
  use_spot: true
  fallback_to_ondemand: true
- name: gpu-worker-g5-1
  instance_type: g5.4xlarge
  resources:
    cpu:
    gpu:
    memory:
    object_store_memory:
    custom_resources:
      worker_node: 1
      "accelerator_type:NVIDIA_TESLA_A10G": 1
  min_workers: 0
  max_workers: 100
  use_spot: true
  fallback_to_ondemand: true
- name: gpu-worker-g5-12
  instance_type: g5.12xlarge
  resources:
    cpu:
    gpu:
    memory:
    object_store_memory:
    custom_resources:
      worker_node: 1
      "accelerator_type:NVIDIA_TESLA_A10G": 1
  min_workers: 0
  max_workers: 100
  use_spot: true
  fallback_to_ondemand: true
- name: gpu-worker-p3
  instance_type: p3.8xlarge
  resources:
    cpu:
    gpu:
    memory:
    object_store_memory:
    custom_resources:
      worker_node: 1
      "accelerator_type:NVIDIA_TESLA_V100": 1
  min_workers: 0
  max_workers: 100
  use_spot: true
  fallback_to_ondemand: true
- name: gpu-worker-p4d
  instance_type: p4d.24xlarge
  resources:
    cpu:
    gpu:
    memory:
    object_store_memory:
    custom_resources:
      worker_node: 1
      "accelerator_type:NVIDIA_A100_40G": 1
      accelerator_type_cpu: 1
  aws_advanced_configurations_json:
    BlockDeviceMappings:
    - DeviceName: /dev/sda1
      Ebs:
        DeleteOnTermination: true
        VolumeSize: 1000
    TagSpecifications:
    - ResourceType: instance
      Tags:
      - Key: as-feature-multi-zone
        Value: "true"
  min_workers: 0
  max_workers: 100
- name: gpu-worker-p4de
  instance_type: p4de.24xlarge
  resources:
    cpu:
    gpu:
    memory:
    object_store_memory:
    custom_resources:
      worker_node: 1
      "accelerator_type:NVIDIA_A100_80G": 1
      accelerator_type_cpu: 1
  aws_advanced_configurations_json:
    BlockDeviceMappings:
    - DeviceName: /dev/sda1
      Ebs:
        DeleteOnTermination: true
        VolumeSize: 1000
    TagSpecifications:
    - ResourceType: instance
      Tags:
      - Key: as-feature-multi-zone
        Value: "true"
  min_workers: 0
  max_workers: 100
aws:
  TagSpecifications:
    - ResourceType: instance
      Tags:
        - Key: as-feature-enable-multi-az-serve
          Value: 1
