head_node_type:
  name: head-node-type
  instance_type: n2-standard-32
  resources:
    cpu:
    gpu:
    memory:
    object_store_memory:
    custom_resources:
      head_node: 1
      accelerator_type_cpu: 1
worker_node_types:
- name: cpu-worker
  instance_type: n2-standard-4
  resources:
    cpu:
    gpu:
    memory:
    object_store_memory:
    custom_resources:
      worker_node: 1
      accelerator_type_cpu: 1
  min_workers: 0
  max_workers: 100
  use_spot: false
- name: gpu-worker-t4-1
  instance_type: n1-standard-16-nvidia-t4-16gb-1
  resources:
    cpu:
    gpu:
    memory:
    object_store_memory:
    custom_resources:
      worker_node: 1
      "accelerator_type:NVIDIA_TESLA_T4": 1
  min_workers: 0
  max_workers: 100
  use_spot: true
  fallback_to_ondemand: true
- name: gpu-worker-l4-1
  instance_type: g2-standard-16-nvidia-l4-1
  resources:
    cpu:
    gpu:
    memory:
    object_store_memory:
    custom_resources:
      worker_node: 1
      "accelerator_type:NVIDIA_L4": 1
  min_workers: 0
  max_workers: 100
  use_spot: true
  fallback_to_ondemand: true
- name: gpu-worker-l4-2
  instance_type: g2-standard-24-nvidia-l4-2
  resources:
    cpu:
    gpu:
    memory:
    object_store_memory:
    custom_resources:
      worker_node: 1
      "accelerator_type:NVIDIA_L4": 1
  min_workers: 0
  max_workers: 100
  use_spot: true
  fallback_to_ondemand: true
- name: gpu-worker-l4-4
  instance_type: g2-standard-48-nvidia-l4-4
  resources:
    cpu:
    gpu:
    memory:
    object_store_memory:
    custom_resources:
      worker_node: 1
      "accelerator_type:NVIDIA_L4": 1
  min_workers: 0
  max_workers: 100
  use_spot: true
  fallback_to_ondemand: true
- name: gpu-worker-l4-8
  instance_type: g2-standard-96-nvidia-l4-8
  resources:
    cpu:
    gpu:
    memory:
    object_store_memory:
    custom_resources:
      worker_node: 1
      "accelerator_type:NVIDIA_L4": 1
  min_workers: 0
  max_workers: 100
  use_spot: true
  fallback_to_ondemand: true
- name: gpu-worker-v100
  instance_type: n1-standard-32-nvidia-v100-16gb-4
  resources:
    cpu:
    gpu:
    memory:
    object_store_memory:
    custom_resources:
      worker_node: 1
      "accelerator_type:NVIDIA_TESLA_V100": 1
  min_workers: 0
  max_workers: 100
  use_spot: true
  fallback_to_ondemand: true
- name: gpu-worker-a100-40g-1 
  instance_type: a2-highgpu-1g-nvidia-a100-40gb-1
  resources:
    cpu:
    gpu:
    memory:
    object_store_memory:
    custom_resources:
      worker_node: 1
      "accelerator_type:NVIDIA_A100_40G": 1
      accelerator_type_cpu: 1
  min_workers: 0
  max_workers: 100
- name: gpu-worker-a100-40g-2 
  instance_type: a2-highgpu-2g-nvidia-a100-40gb-2
  resources:
    cpu:
    gpu:
    memory:
    object_store_memory:
    custom_resources:
      worker_node: 1
      "accelerator_type:NVIDIA_A100_40G": 1
      accelerator_type_cpu: 1
  min_workers: 0
  max_workers: 100
- name: gpu-worker-a100-40g-4 
  instance_type: a2-highgpu-4g-nvidia-a100-40gb-4
  resources:
    cpu:
    gpu:
    memory:
    object_store_memory:
    custom_resources:
      worker_node: 1
      "accelerator_type:NVIDIA_A100_40G": 1
      accelerator_type_cpu: 1
  min_workers: 0
  max_workers: 100
- name: gpu-worker-a100-40g-8 
  instance_type: a2-highgpu-8g-nvidia-a100-40gb-8
  resources:
    cpu:
    gpu:
    memory:
    object_store_memory:
    custom_resources:
      worker_node: 1
      "accelerator_type:NVIDIA_A100_40G": 1
      accelerator_type_cpu: 1
  min_workers: 0
  max_workers: 100
- name: gpu-worker-a100-80g-1
  instance_type: a2-ultragpu-1g-nvidia-a100-80gb-1
  resources:
    cpu:
    gpu:
    memory:
    object_store_memory:
    custom_resources:
      worker_node: 1
      "accelerator_type:NVIDIA_A100_80G": 1
      accelerator_type_cpu: 1
  min_workers: 0
  max_workers: 100
- name: gpu-worker-a100-80g-2
  instance_type: a2-ultragpu-2g-nvidia-a100-80gb-2
  resources:
    cpu:
    gpu:
    memory:
    object_store_memory:
    custom_resources:
      worker_node: 1
      "accelerator_type:NVIDIA_A100_80G": 1
      accelerator_type_cpu: 1
  min_workers: 0
  max_workers: 100
- name: gpu-worker-a100-80g-4
  instance_type: a2-ultragpu-4g-nvidia-a100-80gb-4
  resources:
    cpu:
    gpu:
    memory:
    object_store_memory:
    custom_resources:
      worker_node: 1
      "accelerator_type:NVIDIA_A100_80G": 1
      accelerator_type_cpu: 1
  min_workers: 0
  max_workers: 100
- name: gpu-worker-a100-80g-8
  instance_type: a2-ultragpu-8g-nvidia-a100-80gb-8
  resources:
    cpu:
    gpu:
    memory:
    object_store_memory:
    custom_resources:
      worker_node: 1
      "accelerator_type:NVIDIA_A100_80G": 1
      accelerator_type_cpu: 1
  min_workers: 0
  max_workers: 100
gcp_advanced_configurations_json:
  instance_properties:
    labels:
      as-feature-multi-zone: 'true'
      as-feature-enable-multi-az-serve: 'true'
