head_node_type:
  name: head-node-type
  instance_type: n2-standard-4
  resources:
    cpu: 0
worker_node_types: []
auto_select_worker_config: true
# TODO(shomil): remove once set by default in OA
gcp_advanced_configurations_json:
  instance_properties:
    labels:
      as-feature-multi-zone: 'true'
      as-feature-enable-multi-az-serve: 'true'
