head_node_type:
  name: head-node-type
  instance_type: n2-standard-4
  resources:
    cpu: 0

auto_select_worker_config: true

# This will be ignored since auto_select_worker_config is enabled,
# but must be present to pass backend validation.
# 
# TODO (shomilj): Remove once validation is fixed.
worker_node_types:
- name: cpu-worker
  instance_type: n1-standard-4
  min_workers: 0
  max_workers: 1
  use_spot: false

# TODO(shomil): Remove once set by default in OA.
gcp_advanced_configurations_json:
  instance_properties:
    labels:
      as-feature-multi-zone: 'true'
      as-feature-enable-multi-az-serve: 'true'
