head_node_type:
  name: head
  instance_type: m5.2xlarge
worker_node_types: []

auto_select_worker_config: true
worker_node_types: []

aws:
  TagSpecifications:
    - ResourceType: instance
      Tags:
        - Key: as-feature-multi-zone
          Value: "true"
