head_node_type:
  name: head
  instance_type: m5.2xlarge
  resources:
    cpu: 0

auto_select_worker_config: true

# This will be ignored since auto_select_worker_config is enabled,
# but must be present to pass backend validation.
# TODO (shomilj): Remove once validation is fixed.
worker_node_types:
- name: gpu_worker
  instance_type: g4dn.2xlarge
  min_workers: 0
  max_workers: 1
  use_spot: false

flags:
  allow-cross-zone-autoscaling: true