head_node_type:
  name: head_node_type
  instance_type: g5.4xlarge
worker_node_types:
- name: gpu_worker
  instance_type: g5.4xlarge
  min_workers: 1
  max_workers: 1
  use_spot: false
auto_select_worker_config: true
