head_node_type:
  name: head
  instance_type: m5.2xlarge
  resources:
    cpu: 0
auto_select_worker_config: false
worker_node_types:
- name: gpu-worker-a10g-1
  instance_type: g5.4xlarge
  resources:
    cpu:
    gpu:
    memory:
    object_store_memory:
    custom_resources:
      "accelerator_type:A10G": 1
  min_workers: 1
  max_workers: 1
flags:
  allow-cross-zone-autoscaling: false
