head_node_type:
  name: head
  instance_type: n2-standard-8
  resources:
    cpu: 0
auto_select_worker_config: false
worker_node_types:
- name: gpu-worker-t4-1
  instance_type: n1-standard-8-nvidia-t4-16gb-1
  resources:
    cpu:
    gpu:
    memory:
    object_store_memory:
    custom_resources:
      "accelerator_type:T4": 1
  min_workers: 1
  max_workers: 1
flags:
  allow-cross-zone-autoscaling: false
