head_node_type:
  name: head_node_type
  instance_type: n2-standard-8

worker_node_types:
- name: gpu_worker
  instance_type: g2-standard-16-nvidia-l4-1
  min_workers: 0
  max_workers: 100
  use_spot: false
