head_node_type:
  name: head-node
  instance_type: m5.2xlarge
  resources:
    cpu: 0
# TODO: revert this
#worker_node_types: []
#auto_select_worker_config: true
worker_node_types:
  - name: worker-node
    instance_type: g5.4xlarge
    resources:
      custom_resources:
        "accelerator_type:T4": 1
      cpu: 64
      gpu: 8
    min_workers: 1
    max_workers: 1
