model_id: meta-llama/Meta-Llama-3.1-8B-Instruct
train_path: s3://...
valid_path: s3://...
num_epochs: 3
learning_rate: 1e-4
deepspeed:
  config_path: configs/deepspeed/zero_3_llama_2_7b.json
worker_resources:
    accelerator: ...
lora_config:
  rank: 8