model_id: meta-llama/Llama-2-13b-hf
train_path: s3://air-example-data/gsm8k/train.jsonl
valid_path: s3://air-example-data/gsm8k/test.jsonl
context_length: 4096
num_devices: 8
num_epochs: 10
train_batch_size_per_device: 8
eval_batch_size_per_device: 8
learning_rate: 5e-6
num_checkpoints_to_keep: 1
output_dir: /mnt/local_storage
deepspeed:
  config_path: deepspeed_configs/zero_3_llama_2_13b.json
flash_attention_2: true
worker_resources:
  g5.12xlarge: 1
