model_id: meta-llama/Llama-2-7b-hf
train_path: s3://air-example-data/gsm8k/train.jsonl
valid_path: s3://air-example-data/gsm8k/test.jsonl
context_length: 512
num_devices: 16
num_epochs: 10
train_batch_size_per_device: 16
eval_batch_size_per_device: 16
learning_rate: 5e-6
num_checkpoints_to_keep: 1
output_dir: /mnt/local_storage
deepspeed:
  config_path: deepspeed_configs/zero_3_llama_2_7b.json
flash_attention_2: true
worker_resources:
  g5.4xlarge: 1
